### ISSUE TITLE
Failed to install on Windows

### ISSUE THREAD

**Issue by PrisionMike** [FloGa/upnp-daemon#1]
I probably should have seen this coming but I thought Win 10 supports bash so it shouldn't be a problem. Anyway, any way I can use it on Windows?
Gratitude for this work BTW. It seems very spot on and well built.

**Comment by FloGa** [comment]
Hello and thank you for showing interest in my project!

Usually I do not develop with Windows in mind, because tasks that are quite simple on Linux can be quite cumbersome on Windows.

However, I looked into your case and it seems Windows does not like the daemonize library, since it uses Unix specific extensions. I might be able to make daemonizing optional and exclusive to Unix. This way, you could run the program in `oneshot` mode on Windows, maybe even periodically with a task scheduler for Windows. Will this suit your needs?

Maybe in the future I'll find a daemonizing library that can run on both Linux and Windows. But for an immediate solution, I'm afraid this is all I can offer.

Let me know what you think!

**Comment by PrisionMike** [comment]
Thank you for the response.
I have barely begun in UPnP. Your project is how I came to know that there is a duration for which the port can be opened. I want the route to be active throught the duration my system is on. Do you think that is possible in oneshot without the daemon? I can put a practical number like `8hrs.to_seconds()` to it though.

I am just using UPnP as a substitute to manual port forwarding for connecting to my Win System via internet. You can help me way better here.

**Comment by FloGa** [comment]
As I stated in the README file, some routers just do not respect the duration field, so even if you tell them to open the port for exactly eight hours, you have no guarantee that the port forwarding is working for eight hours straight and that it is deleted afterwards. You can try it, of course, but I would not rely on it. For example, if your router gets rebooted through the day, maybe manually, maybe after a firmware update, maybe due to power outage, then usually the UPnP table gets cleared.

This is why I created this daemon in the first place. What I can recommend you, I can make the `daemon`-mode optional, so you can install it on Windows. Then, via the Windows Task Scheduler, you can create a new task that calls the "daemon" in `oneshot`-mode every 5 minutes. In your config file you can define a duration of one hour. It then does not matter if you router will respect this duration or not. If you turn off your system, even if the port forwarding is still active, it will not reach your system, since it is off. Usually, IP addresses do not get re-used so quickly that this might be a problem.

I will add another item on my todo list: The possibility of removing an open port. This way, even the last scenario can be handled, and you can remove all open ports prior to turning off your system.

**Comment by FloGa** [comment]
I just released version 0.2.0 to crates.io. This release makes the dependency to daemonize only available to UNIX users, so you should have no problems to install it on Windows. I just tested it myself in a virtual machine.

You now have two options: You can use the program normally on Windows, then it will run in the foreground, but acts in a daemon like manner, periodically updating the open ports. Maybe you find a Windows program that "hides" the terminal window, or you start it minimized via a Batch file.

The second option would be to take my advice and run it in oneshot mode via the Windows Task Scheduler.

Furthermore, I added the possibility of removing ports defined in the configuration file via two new command line flags: `--close-ports-on-exit` and `--only-close-ports`. The first can be used in normal operation mode, to close all defined ports when the program exits. The second flag can be used, when periodically calling oneshot mode. Before shutdown, call the program once with the `--only-close-ports` flag to clean up.

**Comment by PrisionMike** [comment]
I will try it and get back to it ASAP.
Thank you for being so kind. I am new to GitHub, Rust, UPnP. Projects and responses like these make the expedition so much less daunting.

**Comment by FloGa** [comment]
Have you had time to test the new version yet? If so and if it works, then we can close this issue. Don't hesitate to come back if you still have problems.

**Comment by FloGa** [comment]
Due to lack of activity, I will close this issue for now. I addressed the described problem and published a fix.

If you still have problems, please re-open this issue or open a new one.

**Comment by PrisionMike** [comment]
I am so sorry. I had other unavoidable engagements that made testing it impossible. Most of all I didn't have a router that could successfull implement port mapping let alone UPnP.
I did try to use it. I was hit with another error. It couldn't read my ports.csv file. I tried saving it in different directories too.
Allow me to test it again and get back to you

**Comment by PrisionMike** [comment]
Sorry. The installation is fine. The error was on my part. I'll try using it let you know if I have other issues. Thanks a ton for all your effort. Really thank you

**Comment by FloGa** [comment]
I'm glad to hear that the installation works now! :+1:
